export default {
    ADD_USER: 'ADD_USER',
    REMOVE_USER: 'REMOVE_USER',
    ADD_SERVICE: 'ADD_SERVICE',
    REMOVE_SERVICE: 'REMOVE_SERVICE',
    LOAD_MY_SERVICES: 'LOAD_MY_SERVICES',
    REMOVE_MY_SERVICES: 'REMOVE_MY_SERVICES'
  };
  